name: GuildBattles
version: 1.0-SNAPSHOT
main: locb.both.guildbattles.GuildBattles
api-version: 1.18
commands:
  guild:
    description: Main guilds command
    aliases: [g, guild]
    ussage: /guild <args>
  coins:
    description: Coins command
    ussage: /coins <args>
    permission: guilds.eco
permissions:
  guild.use:
    default: true
  guilds.eco:
    default: op
depend: [Vault]